# Use the official ROS Melodic desktop full image as base
FROM osrf/ros:noetic-desktop-full-focal

# Set non-interactive frontend for apt
ENV DEBIAN_FRONTEND=noninteractive

# Update and upgrade system
RUN apt-get update && \
    rosdep update

RUN apt-get install -y git-all libignition-math4-dev curl figlet net-tools

# Install interbotix dependencies
WORKDIR /home
COPY xsarm_rpi4_install.sh .
RUN chmod +x xsarm_rpi4_install.sh
RUN ./xsarm_rpi4_install.sh -d noetic -p /home/interbotix_ws -n
RUN bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && \
    source /home/interbotix_ws/devel/setup.bash"
RUN echo "source /home/interbotix_ws/devel/setup.bash" >> ~/.bashrc

# Expose the ports for the ROS master
EXPOSE 11311
